name: Static Analysis

on:
    push:

jobs:
    php-lint:
        name: PHP lint
        runs-on: 'ubuntu-latest'
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "8.3"
                    - "8.4"
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v3

            -   name: Run PHP lint
                run: composer run lint-php

    phpstan:
        name: PHPStan
        runs-on: 'ubuntu-latest'
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "8.3"
                    - "8.4"
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v3

            -   name: Run PHPStan
                run: composer run lint-php
